[package]
name = "node-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
curve = { package = "srml-staking-npos-reward-curve", path = "../npos-reward-curve"}
